"""
Storyboard — the narrative layer loaded once per world before the game starts.

Generated by StoryboardGenerator from the world JSON, stored as
world_XXX_storyboard.json alongside the world file. The game loads it at
startup; if missing it is generated automatically on first load.

The Storyboard is the single source of truth for:
  - The human story (victim, threat, stakes, timeline)
  - Adapted persona descriptions per world genre (kills the sci-fi contamination
    problem: a Systems Operator in a manor mystery no longer talks about power surges)
  - Pre-written discovery beats (retrieved, not generated at runtime)
  - Room story roles (shapes room-entry narration)
  - Conversation seeds (surface evidence the human reader needs to deduce)
  - The solution (sealed — never shown to the narrator, only used for validation)

All fields default to empty so a failed or missing storyboard degrades
gracefully — the game continues with generic narration.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


SCHEMA_VERSION = "1"


# ── Sub-schemas ────────────────────────────────────────────────────────────── #

@dataclass
class StoryboardMystery:
    """The authoritative mystery facts generated by the storyboard LLM.

    Generated once and stored in the storyboard JSON. All downstream layers
    (narrator, deduction validation) read from here — not from the world JSON.
    """
    victim: str = ""
    killer_name: str = ""
    proof_object_id: str = ""
    motive_hint: str = ""

    def is_empty(self) -> bool:
        return not self.killer_name

    @classmethod
    def from_dict(cls, d: dict) -> "StoryboardMystery":
        def _s(v) -> str:
            return v if isinstance(v, str) else ""
        return cls(
            victim=_s(d.get("victim")),
            killer_name=_s(d.get("killer_name")),
            proof_object_id=_s(d.get("proof_object_id")),
            motive_hint=_s(d.get("motive_hint")),
        )

    def to_dict(self) -> dict:
        return {
            "victim": self.victim,
            "killer_name": self.killer_name,
            "proof_object_id": self.proof_object_id,
            "motive_hint": self.motive_hint,
        }


@dataclass
class StoryboardPersona:
    """Adapted identity for one character in this specific world genre."""
    world_role: str = ""
    voice: str = ""
    vocabulary: list[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict) -> "StoryboardPersona":
        return cls(
            world_role=d.get("world_role", ""),
            voice=d.get("voice", ""),
            vocabulary=d.get("vocabulary", []),
        )

    def to_dict(self) -> dict:
        return {"world_role": self.world_role, "voice": self.voice, "vocabulary": self.vocabulary}


@dataclass
class StoryboardSolution:
    """The sealed answer used only for human deduction validation.

    Never passed to the narrator. Never written to game logs.
    """
    question: str = ""
    answer: str = ""
    answer_aliases: list[str] = field(default_factory=list)
    answer_type: str = "person"
    motive: str = ""
    proof_object: str = ""
    proof_sentence: str = ""
    hint_1: str = ""
    hint_2: str = ""
    victory_narration_hook: str = ""
    defeat_narration_hook: str = ""

    def is_empty(self) -> bool:
        return not self.answer

    def matches(self, human_answer: str) -> bool:
        """True if the human's answer matches the canonical answer or any alias."""
        normalized = _normalize(human_answer)
        if not normalized:
            return False
        canonical = _normalize(self.answer)
        if normalized == canonical:
            return True
        aliases = [_normalize(a) for a in self.answer_aliases]
        if normalized in aliases:
            return True
        # Substring match: "pemberton" inside "lord pemberton" and vice versa.
        return any(
            normalized in alias or alias in normalized
            for alias in aliases
            if alias
        )

    @classmethod
    def from_dict(cls, d: dict) -> "StoryboardSolution":
        def _s(v) -> str:
            return v if isinstance(v, str) else ""
        return cls(
            question=_s(d.get("question")),
            answer=_s(d.get("answer")),
            answer_aliases=[a for a in d.get("answer_aliases", []) if isinstance(a, str)],
            answer_type=_s(d.get("answer_type")) or "person",
            motive=_s(d.get("motive")),
            proof_object=_s(d.get("proof_object")),
            proof_sentence=_s(d.get("proof_sentence")),
            hint_1=_s(d.get("hint_1")),
            hint_2=_s(d.get("hint_2")),
            victory_narration_hook=_s(d.get("victory_narration_hook")),
            defeat_narration_hook=_s(d.get("defeat_narration_hook")),
        )

    def to_dict(self) -> dict:
        return {
            "question": self.question,
            "answer": self.answer,
            "answer_aliases": self.answer_aliases,
            "answer_type": self.answer_type,
            "motive": self.motive,
            "proof_object": self.proof_object,
            "proof_sentence": self.proof_sentence,
            "hint_1": self.hint_1,
            "hint_2": self.hint_2,
            "victory_narration_hook": self.victory_narration_hook,
            "defeat_narration_hook": self.defeat_narration_hook,
        }


# ── Main schema ────────────────────────────────────────────────────────────── #

@dataclass
class Storyboard:
    """Complete narrative layer for one world.

    Loaded once at game start. Immutable during a session.
    """
    world_id: str = ""
    generated_at: str = ""
    schema_version: str = SCHEMA_VERSION

    # Plot — the human story behind the mechanical puzzle.
    plot_victim: str = ""
    plot_threat: str = ""
    plot_stakes: str = ""
    plot_timeline: str = ""
    plot_tension_hint: str = ""
    plot_atmosphere: str = ""
    plot_protagonist_context: str = ""

    # Per-character world adaptation (replaces raw role/skills in all LLM calls).
    adapted_personas: dict[str, StoryboardPersona] = field(default_factory=dict)

    # Per-room narrative role.
    room_stories: dict[str, str] = field(default_factory=dict)

    # Per-object: one pre-written sentence emitted on first discovery (no LLM call).
    discovery_beats: dict[str, str] = field(default_factory=dict)

    # Narrator tone guidance by story phase.
    phase_guidance: dict[str, str] = field(default_factory=dict)

    # Per-character: observations rooted in the plot, consumed during the game.
    conversation_seeds: dict[str, list[str]] = field(default_factory=dict)

    # Ending flavor.
    ending_guidance: dict[str, str] = field(default_factory=dict)

    # Suspects — visible to the narrator (names + motives) but killer identity is sealed.
    # Each entry: {"name": str, "connection_to_victim": str, "apparent_motive": str}
    # The is_killer flag is stripped at load time so narrator never sees it.
    suspects: list[dict] = field(default_factory=list)

    # Generated mystery — the authoritative who/what/why, owned by the storyboard.
    # Populated by the storyboard LLM; never requires a mystery block in the world JSON.
    mystery: StoryboardMystery = field(default_factory=StoryboardMystery)

    # Sealed — never passed to the narrator; only used for deduction validation.
    solution: StoryboardSolution = field(default_factory=StoryboardSolution)

    # ── Query API ─────────────────────────────────────────────────────────── #

    def is_empty(self) -> bool:
        return not any([self.plot_victim, self.plot_threat, self.room_stories])

    def lore_excerpt(
        self,
        *,
        actor_name: str = "",
        room_id: str = "",
        object_id: str = "",
    ) -> str:
        """Compact plot context for a single narrator beat.

        Only the fields relevant to the current turn — keeps prompt small.
        """
        parts: list[str] = []
        if self.plot_victim:
            parts.append(f"THE VICTIM: {self.plot_victim}")
        if self.plot_tension_hint:
            parts.append(f"TENSION: {self.plot_tension_hint}")
        if self.plot_atmosphere:
            parts.append(f"ATMOSPHERE: {self.plot_atmosphere}")
        if actor_name:
            persona = self.adapted_personas.get(actor_name)
            if persona and persona.voice:
                parts.append(f"VOICE ({actor_name}): {persona.voice}")
        if room_id and room_id in self.room_stories:
            parts.append(f"THIS ROOM: {self.room_stories[room_id]}")
        if object_id and object_id in self.discovery_beats:
            parts.append(f"THIS OBJECT: {self.discovery_beats[object_id]}")
        return "\n".join(parts)

    def persona_for(self, name: str) -> StoryboardPersona | None:
        return self.adapted_personas.get(name)

    def discovery_beat(self, object_id: str) -> str:
        return self.discovery_beats.get(object_id, "")

    def room_story(self, room_id: str) -> str:
        return self.room_stories.get(room_id, "")

    def phase_for_turn(self, turn: int, total_turns: int = 40) -> str:
        """Map a turn number to a story phase name."""
        ratio = turn / max(total_turns, 1)
        if ratio < 0.25:
            return "establishing"
        if ratio < 0.6:
            return "investigating"
        if ratio < 0.85:
            return "converging"
        return "revealing"

    def phase_guidance_for_turn(self, turn: int, total_turns: int = 40) -> str:
        phase = self.phase_for_turn(turn, total_turns)
        return self.phase_guidance.get(phase, "")

    def ending_text(self, won: bool, wrong_deduction: bool = False) -> str:
        if wrong_deduction:
            return self.ending_guidance.get("lost_by_wrong_deduction", "")
        return self.ending_guidance.get("won" if won else "lost", "")

    def pop_seed(self, actor_name: str, used: set[str]) -> str | None:
        """Return the next unused conversation seed for this actor, or None."""
        for seed in self.conversation_seeds.get(actor_name, []):
            if seed not in used:
                return seed
        return None

    def suspects_context(self) -> str:
        """Return a formatted suspects list for the narrator — without flagging who is guilty."""
        if not self.suspects:
            return ""
        lines = []
        for s in self.suspects:
            if not isinstance(s, dict):
                continue
            name = s.get("name", "")
            connection = s.get("connection_to_victim", "")
            motive = s.get("apparent_motive", "")
            if name:
                entry = f"- {name}: {connection}"
                if motive:
                    entry += f" Apparent motive: {motive}"
                lines.append(entry)
        return "\n".join(lines)

    # ── Serialisation ─────────────────────────────────────────────────────── #

    def to_dict(self) -> dict:
        return {
            "world_id": self.world_id,
            "generated_at": self.generated_at,
            "schema_version": self.schema_version,
            "mystery": self.mystery.to_dict(),
            "plot": {
                "victim": self.plot_victim,
                "threat": self.plot_threat,
                "stakes": self.plot_stakes,
                "timeline": self.plot_timeline,
                "tension_hint": self.plot_tension_hint,
                "atmosphere": self.plot_atmosphere,
                "protagonist_context": self.plot_protagonist_context,
            },
            "adapted_personas": {
                name: p.to_dict() for name, p in self.adapted_personas.items()
            },
            "suspects": self.suspects,
            "room_stories": self.room_stories,
            "discovery_beats": self.discovery_beats,
            "phase_guidance": self.phase_guidance,
            "conversation_seeds": self.conversation_seeds,
            "ending_guidance": self.ending_guidance,
            "solution": self.solution.to_dict(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Storyboard":
        plot = data.get("plot", {})
        personas_raw = data.get("adapted_personas", {})
        solution_raw = data.get("solution", {})
        mystery_raw = data.get("mystery", {})
        return cls(
            world_id=data.get("world_id", ""),
            generated_at=data.get("generated_at", ""),
            schema_version=data.get("schema_version", SCHEMA_VERSION),
            mystery=StoryboardMystery.from_dict(mystery_raw) if isinstance(mystery_raw, dict) else StoryboardMystery(),
            plot_victim=plot.get("victim", ""),
            plot_threat=plot.get("threat", ""),
            plot_stakes=plot.get("stakes", ""),
            plot_timeline=plot.get("timeline", ""),
            plot_tension_hint=plot.get("tension_hint", ""),
            plot_atmosphere=plot.get("atmosphere", ""),
            plot_protagonist_context=plot.get("protagonist_context", ""),
            adapted_personas={
                name: StoryboardPersona.from_dict(v)
                for name, v in personas_raw.items()
                if isinstance(v, dict)
            },
            suspects=[
                {k: v for k, v in s.items() if k != "is_killer"}
                for s in data.get("suspects", [])
                if isinstance(s, dict) and s.get("name")
            ],
            room_stories={
                k: v if isinstance(v, str) else ""
                for k, v in data.get("room_stories", {}).items()
            },
            discovery_beats={
                k: v if isinstance(v, str) else ""
                for k, v in data.get("discovery_beats", {}).items()
            },
            phase_guidance={
                k: v if isinstance(v, str) else ""
                for k, v in data.get("phase_guidance", {}).items()
            },
            conversation_seeds={
                name: [s for s in seeds if isinstance(s, str)]
                for name, seeds in data.get("conversation_seeds", {}).items()
                if isinstance(seeds, list)
            },
            ending_guidance={
                k: v if isinstance(v, str) else ""
                for k, v in data.get("ending_guidance", {}).items()
            },
            solution=StoryboardSolution.from_dict(solution_raw),
        )

    @classmethod
    def from_file(cls, path: Path) -> "Storyboard":
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls.from_dict(data)

    def save(self, path: Path) -> None:
        path.write_text(
            json.dumps(self.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )


# ── Helpers ────────────────────────────────────────────────────────────────── #

def _normalize(text: str) -> str:
    """Lowercase, strip punctuation and extra whitespace for answer matching."""
    text = text.lower()
    text = re.sub(r"[^\w\s]", "", text)
    return re.sub(r"\s+", " ", text).strip()


def humanize_text(text: str) -> str:
    """Replace snake_case object IDs embedded in prose with spaced words.

    e.g. "check stained_table" → "check stained table"
    Only touches all-lowercase tokens with at least one underscore.
    Leaves proper nouns, uppercase acronyms, and plain prose untouched.
    """
    return re.sub(
        r"\b([a-z][a-z0-9]*(?:_[a-z0-9]+)+)\b",
        lambda m: m.group(0).replace("_", " "),
        text,
    )


def storyboard_path_for(world_path: Path) -> Path:
    """Return the expected storyboard path for a given world JSON path."""
    return world_path.with_name(world_path.stem + "_storyboard.json")


def is_storyboard_stale(world_path: Path, storyboard_path: Path) -> bool:
    """True if the storyboard is missing or older than the world JSON."""
    if not storyboard_path.exists():
        return True
    return world_path.stat().st_mtime > storyboard_path.stat().st_mtime
